# Generated by Django 5.1.4 on 2024-12-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thought',
            name='thought',
            field=models.TextField(),
        ),
    ]
